CREATE TABLE IF NOT EXISTS `#__fotos_perfils` (
	`id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(255) NOT NULL,
	`correo` VARCHAR(255) NOT NULL,
	`ext` VARCHAR(255) NOT NULL,
	`imagen` VARCHAR(255) NOT NULL,
	`cita` VARCHAR(500) NOT NULL,
	'cargo' VARCHAR(500) NOT NULL,
	`datos` VARCHAR(255) NOT NULL,
	`created_by` INT(11) NOT NULL,
	`state` INT(11) NOT NULL,
	`ordering` INT(11) NOT NULL,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB COMMENT="" DEFAULT COLLATE=utf8_general_ci;
